#index:
#    path: /
#    controller: App\Controller\DefaultController::index

sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /
    
app_directory:
    resource: "../src/Resources/config/routing/routing.yml"
    prefix:   /
